name: Build de imagenes v2.

on:
  push:
    branches:
      - 'master'
      
jobs:
  build_prueba_de_container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v3
    - name: Setup del JDK.
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build con Mave.
      run: mvn -B package --file pom.xml

    - name: Login a Docker Hub  
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push a Docker Hub de orders-service-example
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ignaciomontero2022/orders-service-example:${{ github.sha }}